apiVersion: v1
kind: Service
metadata:
  name: simple-node-api-service
spec:
  type: NodePort
  selector:
    app: sample-node-app-api
  ports:
  - port: 7000
    targetPort: 3000
    nodePort: 30127
