apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-node-app-api
  template:
    metadata:
      labels:
        app: sample-node-app-api
    spec:
      containers:
      - name: sample-node-api-conatainer
        image: sumit855/sample-node-app
        ports:
        - containerPort: 3000